on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    strategy:
      matrix:
        features: [ libsystemd-sys, open ]
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repos
        run: sudo apt update
      - name: Install systemd dependency
        run: sudo apt install libsystemd-dev pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features ${{ matrix.features }}

  test:
    strategy:
      matrix:
        features: [ libsystemd-sys, open ]
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repos
        run: sudo apt update
      - name: Install systemd dependency
        run: sudo apt install libsystemd-dev pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features ${{ matrix.features }}
        timeout-minutes: 6

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repos
        run: sudo apt update
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repos
        run: sudo apt update
      - name: Install systemd dependency
        run: sudo apt install libsystemd-dev pkg-config
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings